### ISSUE TITLE
All tables created with this extension are only read/written to/from S3? (no local disk usage, correct?)

### ISSUE THREAD

**Issue by titanism** [jrhy/s3db#285]
Reading into the source it appears that all tables created with this extension (e.g. create virtual table) are using S3 for read/writes.  Can you elaborate more on how this works?

**Comment by jrhy** [comment]
You can use s3db in a totally no-local-state way, or you can also use s3db in a way where the database you do `CREATE VIRTUAL TABLE` in is a local file, those tables become part of the database, and don't need to be recreated next time the database is loaded. For applications, probably the former is more convenient, but for interactive use, the latter has been convenient for me.
