### ISSUE TITLE
More docs

### ISSUE THREAD

**Issue by frioux** [jrhy/s3db#3]
Lots of detail lacking for some of these, should have more docs re what they are and why one might set them:

 * https://github.com/jrhy/s3db/blob/5306fffe9b20f8c67da8fd9fc46490cd481730d5/s3db.go#L52-L59
 * https://github.com/jrhy/s3db/blob/5306fffe9b20f8c67da8fd9fc46490cd481730d5/s3db.go#L601
 * https://github.com/jrhy/s3db/blob/5306fffe9b20f8c67da8fd9fc46490cd481730d5/s3db.go#L605

And more, but just grabbed some easy to find examples

**Comment by jrhy** [comment]
Thanks for the feedback! I've added godoc that answers these questions and am working on some more.

**Comment by jrhy** [comment]
This package is all about the SQL now, instead of the Go packages directly, and the README has taken over as the main source of documentation.
